# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /posts/:title

# Setup
title:               purezen_
tagline:             'learning the way of the code..'
description:         'A budding developer from New Delhi NCR, India'
url:                 http://purezen.github.io
baseurl:             /
paginate:            7

google_analytics: 'UA-59678197-1'
disqus_shortname: purezen

sass:
  sass_dir: _sass
  style:    compressed

# About/contact
author:
  name:             Aditya Bhardwaj
  url:              https://twitter.com/purezen_
  email:            aditya2204@gmail.com
  github:           purezen
  twitter:          purezen_
  reddit:           purezen
  linkedin:         purezen
  quora:            Aditya-Bhardwaj-4
  stackoverflow:    1509855/purezen

# Custom vars
version:             1.0.0
